version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wannago
      MYSQL_USER: wannago_user
      MYSQL_PASSWORD: wannago_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: $DOCKER_USERNAME/wannago
    container_name: wannago-app
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wannago
      SPRING_DATASOURCE_USERNAME: wannago_user
      SPRING_DATASOURCE_PASSWORD: wannago_pass

volumes:
  mysql-data: